name: Windows

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      # explicit include-based build matrix, of known valid options
      matrix:
        include:
          - os: windows-2019
            visual_studio: "Visual Studio 16 2019"
    env:
      build_dir: "build"
      config: "Release"

    steps:
      - uses: actions/checkout@v2

      - name: Remove python3
        run: |
          Remove-Item "C:/hostedtoolcache/windows/Python/3.7.9/x64/python3.exe"
          
      - name: Create python3 as a copy
        run: |
          New-Item -ItemType HardLink -Path "C:/hostedtoolcache/windows/Python/3.7.9/x64/python3.exe" -Target "C:/hostedtoolcache/windows/Python/3.7.9/x64/python.exe"
          
      - name: python3 --version.
        run: |
          which python3
          python3 --version
          
      - name: create venv with python
        run: |
          python3 -m venv py3-env
          ls py3-env

      - name: Configure CMake
        id: configure
        run: cmake . -B ${{ env.build_dir }} -G "${{ matrix.visual_studio }}" -A x64
        shell: bash


      # - name: Build
      #   run: cmake --build . --config ${{ env.config }} --target all --verbose
      #   working-directory: ${{ env.build_dir }}