name: Windows

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      # explicit include-based build matrix, of known valid options
      matrix:
        include:
          - os: windows-2019
            visual_studio: "Visual Studio 16 2019"
    env:
      build_dir: "build"
      config: "Release"

    steps:
      - uses: actions/checkout@v2

      - name: Remove python3
        run: |
          Remove-Item "C:/hostedtoolcache/windows/Python/3.9.1/x64/python3.exe"
          
      - name: Create python3b as a copy
        run: |
          Copy-Item "C:/hostedtoolcache/windows/Python/3.9.1/x64/python.exe" -Destination "C:/hostedtoolcache/windows/Python/3.9.1/x64/python3b.exe"
          
      - name: python3b --version.
        run: |
          which python3b
          python3b --version

          
      - name: create venv with python
        run: |
          python3b -m venv py-env
          ls py3b-env
          



      - name: Configure CMake
        id: configure
        run: cmake . -B ${{ env.build_dir }} -G "${{ matrix.visual_studio }}" -A x64
        shell: bash


      # - name: Build
      #   run: cmake --build . --config ${{ env.config }} --target all --verbose
      #   working-directory: ${{ env.build_dir }}